version: '2'


services:
    
    loadbalancer:
        build:
            context: ./LogBalancer
            dockerfile: Dockerfile
        container_name: logbalancer
        ports:
            - "8000:6001"
            
    db:
        image: mongo:latest
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod


volumes:
    mongodb:
    mongodb_config: